"""add_address_table

Revision ID: bdf7b174cb4a
Revises: 3ccf86dbefd3
Create Date: 2023-04-06 09:50:42.267119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf7b174cb4a'
down_revision = '3ccf86dbefd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
