"""add_role_table

Revision ID: 217cf4fff493
Revises: a03967718f7f
Create Date: 2023-04-06 09:49:05.982723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217cf4fff493'
down_revision = 'a03967718f7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('name', sa.Enum('ADMIN', 'STORE_OWNER', 'CUSTOMER', name='roleenum'), server_default='CUSTOMER', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    # ### end Alembic commands ###
