"""add_user_table

Revision ID: 3ccf86dbefd3
Revises: 217cf4fff493
Create Date: 2023-04-06 09:50:05.716785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ccf86dbefd3'
down_revision = '217cf4fff493'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
