"""add_order_table

Revision ID: 29ddfd7c7b59
Revises: bdf7b174cb4a
Create Date: 2023-04-06 09:52:01.441671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ddfd7c7b59'
down_revision = 'bdf7b174cb4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
